name: Test

on:
  - push

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-16.04
          # TODO Uncomment once macos-latest switches to macos-11.0
          #      https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
          # - macos-10.15
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm test
